import type { DriverRecord } from "./driverRoster";

// Six hand-authored rows matching the shared screenshot, split out from
// driverRoster.ts once it passed the 150-line limit (same split already done
// for customers' customerDetailsData.ts).
export const handAuthoredDrivers: DriverRecord[] = [
  {
    id: "DR-08190",
    name: "Marcus Thorne",
    vehicle: "Ford Transit (2022)",
    plate: "RFJ-341",
    vehicleType: "Cargo Van",
    status: "online",
    rating: 4.8,
    deliveries: 1240,
    onTimeRate: 98.5,
    earnings: 3158.0,
    earningsDeltaPct: 4.5,
  },
  {
    id: "DR-08404",
    name: "Elena Rodriguez",
    vehicle: "Mercedes Sprinter",
    plate: "SPR-772",
    vehicleType: "Sprinter Van",
    status: "online",
    rating: 4.9,
    deliveries: 856,
    onTimeRate: 96.7,
    earnings: 3150.0,
    earningsDeltaPct: 0,
  },
  {
    id: "DR-08305",
    name: "James Smith",
    vehicle: "Ford Transit",
    plate: "FTS-205",
    vehicleType: "Cargo Van",
    status: "in-transit",
    rating: 4.7,
    deliveries: 920,
    onTimeRate: 96.7,
    earnings: 2859.0,
    earningsDeltaPct: -1.8,
  },
  {
    id: "DR-08422",
    name: "James Wilson",
    vehicle: "Iveco Daily",
    plate: "IVD-118",
    vehicleType: "Box Truck",
    status: "offline",
    rating: 4.5,
    deliveries: 2104,
    onTimeRate: 94.1,
    earnings: 3150.0,
    earningsDeltaPct: 0,
  },
  {
    id: "DR-08489",
    name: "Maria Garcia",
    vehicle: "Ram ProMaster",
    plate: "RPM-089",
    vehicleType: "Cargo Van",
    status: "delivered",
    rating: 5.0,
    deliveries: 740,
    onTimeRate: 99.2,
    earnings: 3500.0,
    earningsDeltaPct: 3.2,
  },
  {
    id: "DR-08307",
    name: "David Johnson",
    vehicle: "Nissan NV3500",
    plate: "NV3-500",
    vehicleType: "Box Truck",
    status: "online",
    rating: 4.6,
    deliveries: 800,
    onTimeRate: 95.4,
    earnings: 2750.0,
    earningsDeltaPct: -1.5,
  },
];
