import type { CustomerDetail } from "./customerDetails";

// TODO: replace with GET /customers/:id once the Customer Management API
// exists. Only these two customers have hand-authored detail matching the
// Figma reference — see getCustomerDetail() in customerDetails.ts for the
// generic fallback used by every other mock customer.
export const customerDetails: Record<string, CustomerDetail> = {
  "KR-89210-ER": {
    id: "KR-89210-ER",
    name: "Sarah Jenkins",
    fullName: "Sarah Amelia Jenkins",
    status: "active",
    accountType: "individual",
    joinedDate: "June 12, 2023",
    totalOrders: 142,
    ordersDelta: "12%",
    totalSpent: "$12,450",
    aov: "$87.68",
    preferredType: "Express",
    email: "sarah.j@example.com",
    emailVerified: true,
    phone: "+1 (555) 012-9021",
    phoneVerified: true,
    createdDate: "Jun 12, 2023",
    lastActivity: "2 hours ago",
    phoneVerifiedDate: "Mar 12, 2023",
    emailVerifiedDate: "Mar 12, 2023",
    idVerifiedDate: "Mar 14, 2023",
    fullyVerified: true,
    recentOrders: [
      { id: "#KR-98210", date: "Oct 24, 2023", status: "delivered", amount: "$145.00" },
      { id: "#KR-98188", date: "Oct 18, 2023", status: "delivered", amount: "$89.20" },
      { id: "#KR-98005", date: "Oct 12, 2023", status: "in-transit", amount: "$230.50", route: "Chicago to Miami" },
      { id: "#KR-97992", date: "Oct 5, 2023", status: "delivered", amount: "$64.00" },
      { id: "#KR-97891", date: "Sep 28, 2023", status: "cancelled", amount: "$112.00" },
    ],
    paymentMethods: [
      {
        id: "pm-sj-1",
        type: "card",
        label: "Visa Ending in 4242",
        detail: "Expires 12/26",
        status: "verified",
        isDefault: true,
        cardholderName: "Sarah Jenkins",
        expiry: "12/26",
      },
      {
        id: "pm-sj-2",
        type: "paypal",
        label: "PayPal Business",
        detail: "sarah@example.com",
        status: "verified",
        email: "sarah@example.com",
        connectedDate: "Jan 8, 2023",
      },
      {
        id: "pm-sj-3",
        type: "bank",
        label: "Chase Bank ACH",
        detail: "Verified",
        status: "verified",
        bankName: "Chase Bank",
        accountType: "Checking",
      },
    ],
  },
  "KR-77410-JW": {
    id: "KR-77410-JW",
    name: "Acme Refinery LLC",
    fullName: "Acme Refinery LLC",
    status: "active",
    accountType: "company",
    joinedDate: "June 12, 2023",
    totalOrders: 14292,
    ordersDelta: "12%",
    totalSpent: "$84,920",
    aov: "$267.04",
    preferredType: "Freight",
    email: "s.jenkins@globallogistics.com",
    emailVerified: true,
    phone: "+1 (713) 555-0144",
    phoneVerified: true,
    createdDate: "Jun 12, 2023",
    lastActivity: "2 hours ago",
    phoneVerifiedDate: "Mar 12, 2023",
    emailVerifiedDate: "Mar 12, 2023",
    idVerifiedDate: "Mar 14, 2023",
    fullyVerified: true,
    membershipTier: "Premium Member",
    registrationNumber: "TX-7843291",
    industry: "Oil & Gas",
    location: "Houston, TX",
    creditTerms: {
      creditLimit: 50000,
      outstandingBalance: 32500,
      paymentTerms: "net-15",
      interestRate: 1.5,
      accountStatus: "active",
    },
    recentOrders: [
      { id: "#KR-99410", date: "Nov 2, 2023", status: "delivered", amount: "$1,240.00" },
      { id: "#KR-99377", date: "Oct 29, 2023", status: "in-transit", amount: "$890.50", route: "Local Dispatch" },
      { id: "#KR-99201", date: "Oct 21, 2023", status: "delivered", amount: "$2,100.00" },
      { id: "#KR-99098", date: "Oct 14, 2023", status: "delivered", amount: "$430.00" },
      { id: "#KR-98977", date: "Oct 6, 2023", status: "cancelled", amount: "$675.00" },
    ],
    paymentMethods: [
      {
        id: "pm-jw-1",
        type: "card",
        label: "Visa Ending in 8834",
        detail: "Expires 04/27",
        status: "verified",
        isDefault: true,
        cardholderName: "Acme Refinery LLC",
        expiry: "04/27",
      },
      {
        id: "pm-jw-2",
        type: "bank",
        label: "Wells Fargo ACH",
        detail: "Verified",
        status: "verified",
        bankName: "Wells Fargo",
        accountType: "Business Checking",
      },
      {
        id: "pm-jw-3",
        type: "paypal",
        label: "PayPal Business",
        detail: "billing@acmerefinery.com",
        status: "pending",
        email: "billing@acmerefinery.com",
        connectedDate: "Feb 14, 2024",
      },
    ],
  },
};
