// Builds the US state → city → ZIP lookup used by address pickers in the web
// app and the customer mobile app (2026-09-30).
//
// Source: GeoNames postal codes (https://download.geonames.org/export/zip/US.zip),
// licensed CC BY 4.0 — credit "GeoNames (geonames.org)" wherever the data is
// shown in legal/credits. It lists each ZIP's primary place name; USPS "acceptable"
// alternate city names aren't included.
//
// Usage (from kiaRelay-webapp):
//   curl -L -o US.zip https://download.geonames.org/export/zip/US.zip && unzip US.zip US.txt
//   node scripts/build-us-geo.mjs US.txt
// Writes:
//   public/geo/us/<ST>.json                             (web, fetched per state)
//   ../kiarelay-customer-mobile/assets/data/us-geo/<ST>.json  (mobile, bundled)
//   src/constants/usStates.ts + mobile src/constants/usStates.ts (state list)
import fs from "node:fs";
import path from "node:path";

const input = process.argv[2];
if (!input) throw new Error("Pass the path to GeoNames US.txt");

// 50 states + DC. Territories/military codes (PR, GU, AA/AE/AP, MH…) are out
// of KiaRelay's service area and skipped.
const STATES = {
  AL: "Alabama", AK: "Alaska", AZ: "Arizona", AR: "Arkansas", CA: "California", CO: "Colorado", CT: "Connecticut", DE: "Delaware",
  DC: "District of Columbia", FL: "Florida", GA: "Georgia", HI: "Hawaii", ID: "Idaho", IL: "Illinois", IN: "Indiana", IA: "Iowa",
  KS: "Kansas", KY: "Kentucky", LA: "Louisiana", ME: "Maine", MD: "Maryland", MA: "Massachusetts", MI: "Michigan", MN: "Minnesota",
  MS: "Mississippi", MO: "Missouri", MT: "Montana", NE: "Nebraska", NV: "Nevada", NH: "New Hampshire", NJ: "New Jersey",
  NM: "New Mexico", NY: "New York", NC: "North Carolina", ND: "North Dakota", OH: "Ohio", OK: "Oklahoma", OR: "Oregon",
  PA: "Pennsylvania", RI: "Rhode Island", SC: "South Carolina", SD: "South Dakota", TN: "Tennessee", TX: "Texas", UT: "Utah",
  VT: "Vermont", VA: "Virginia", WA: "Washington", WV: "West Virginia", WI: "Wisconsin", WY: "Wyoming",
};

const byState = new Map();
for (const line of fs.readFileSync(input, "utf8").split("\n")) {
  const [, zip, city, , code] = line.split("\t");
  if (!zip || !city || !STATES[code]) continue;
  const cities = byState.get(code) ?? new Map();
  cities.set(city, [...(cities.get(city) ?? []), zip]);
  byState.set(code, cities);
}

const root = path.resolve(import.meta.dirname, "..");
const webDir = path.join(root, "public/geo/us");
const mobileRoot = path.resolve(root, "../kiarelay-customer-mobile");
const mobileDir = path.join(mobileRoot, "assets/data/us-geo");
for (const dir of [webDir, mobileDir]) fs.mkdirSync(dir, { recursive: true });

let total = 0;
for (const [code, cities] of byState) {
  // Compact: [["Houston", ["77002", "77003", …]], …], cities A→Z, ZIPs ascending.
  const rows = [...cities].sort(([a], [b]) => a.localeCompare(b)).map(([city, zips]) => [city, zips.sort()]);
  const json = JSON.stringify(rows);
  total += json.length;
  fs.writeFileSync(path.join(webDir, `${code}.json`), json);
  fs.writeFileSync(path.join(mobileDir, `${code}.json`), json);
}

const list = Object.entries(STATES)
  .sort(([, a], [, b]) => a.localeCompare(b))
  .map(([code, name]) => `  { code: "${code}", name: "${name}" },`)
  .join("\n");
const header = "// Generated by kiaRelay-webapp/scripts/build-us-geo.mjs — do not edit by hand.\n";
const statesTs = `${header}export interface UsState {\n  code: string;\n  name: string;\n}\n\nexport const US_STATES: UsState[] = [\n${list}\n];\n`;
fs.writeFileSync(path.join(root, "src/constants/usStates.ts"), statesTs);
fs.writeFileSync(path.join(mobileRoot, "src/constants/usStates.ts"), statesTs);

// Mobile can't fetch a file by name at runtime, so it gets a static require map.
const requires = Object.keys(STATES).sort().map((code) => `  ${code}: () => require("../../assets/data/us-geo/${code}.json"),`).join("\n");
fs.writeFileSync(
  path.join(mobileRoot, "src/constants/usGeoFiles.ts"),
  `${header}type CityRows = [city: string, zips: string[]][];\n\nexport const US_GEO_FILES: Record<string, () => CityRows> = {\n${requires}\n};\n`,
);

console.log(`${byState.size} states, ${(total / 1024).toFixed(0)}KB total`);
